name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  file:
    description: 'The properties file path'
    required: true
  property:
    description: 'The property key'
    required: true

# Define your outputs here.
outputs:
  propVal:
    description: 'The property value'

runs:
  using: node16
  main: dist/index.js
