name: 'Read Property'
description: 'Read a value from a Java/JVM properties file'
author: 'Touchlab'

inputs:
  file:
    description: 'The properties file path'
    required: true
  property:
    description: 'The property key'
    required: true

outputs:
  propVal:
    description: 'The property value'

runs:
  using: node24
  main: dist/index.js
